# Generated by Django 3.0.7 on 2020-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateHome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellhomes',
            old_name='RealEstate',
            new_name='agent',
        ),
        migrations.AlterField(
            model_name='sellhomes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
