# Generated by Django 3.0.7 on 2020-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateHome', '0002_auto_20200729_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellhomes',
            name='likes',
        ),
        migrations.AddField(
            model_name='sellhomes',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
