# Generated by Django 3.0.7 on 2020-10-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreateHome', '0003_auto_20200730_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellhomes',
            name='agent',
        ),
        migrations.AddField(
            model_name='sellhomes',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
