# Generated by Django 3.0.7 on 2020-10-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201014_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
