# Generated by Django 3.0.7 on 2020-08-03 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('includes', models.TextField()),
                ('beds', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('price', models.FloatField()),
                ('sqft', models.FloatField()),
                ('newCo', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
                ('video_url', models.URLField()),
                ('website_url', models.URLField()),
                ('address', models.TextField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RentHome.RentHome')),
            ],
        ),
    ]
